[[redirects]]
  from = "/metric"
  to = "/metric/index.html"
  status = 200

[[redirects]]
  from = "/metric/"
  to = "/metric/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[build]
  publish = "public"
  command = "echo 'Static site - no build required'"
