import React from 'react';

export function InsightBox({ summary, model = "AI", flags = {} }) {
  const [expanded, setExpanded] = React.useState(false);

  return (
    <div className="p-4 border rounded-md shadow-sm bg-white">
      <h3 className="text-lg font-semibold mb-2">AI Insight</h3>
      <p>{expanded ? summary : summary.slice(0, 140) + "..."}</p>
      <button onClick={() => setExpanded(!expanded)} className="mt-2 text-blue-600 underline">
        {expanded ? "Show Less" : "Learn More"}
      </button>
      <div className="text-xs text-gray-400 mt-2">Generated by: {model}</div>
      {flags?.lisRisk && <div className="text-red-600 mt-1">⚠️ High LIS Impact</div>}
      {flags?.risLow && <div className="text-yellow-600">⚠️ Low RIS Performance</div>}
    </div>
  );
}
