[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA routing (avoid 404 on refresh/deep links)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optional: prevent CSV caching (your file is public/BlockPlane-clean.csv)
[[headers]]
  for = "/BlockPlane-clean.csv"
  [headers.values]
    Cache-Control = "no-store"
